#!/bin/sh

# Border colors so you can see Alt-Tab working
riverctl border-width 4
riverctl border-color-focused "0x50fa7b" # Bright Green
riverctl border-color-unfocused "0x44475a" # Gray
riverctl map normal Super+Shift R spawn "sh $HOME~/.config/river/init"

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.gGIUABN
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# desktop picture
# riverctl spawn "wbg ~/void_wall.png"
riverctl spawn "/home/xirtus_void/.config/hypr/wallpaper.sh"

# Super+Shift+Return to start an instance of kitty (https://codeberg.org/dnkl/foot)
riverctl map normal Super+Shift Return spawn /usr/bin/kitty
riverctl map normal Super Space spawn fuzzel

# Super+Q to close the focused view
riverctl map normal Super Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

#alt tab for window focus cycle
riverctl map normal Super Tab focus-view next
riverctl map normal Alt+Shift Tab focus-view previous


# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to start an instance of kitty
riverctl map normal Super Return spawn /usr/bin/kitty

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super+Up to switch to a horizontal layout (Main on top, stack on bottom)
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"

# Super+Down to switch back to vertical (Main on left, stack on right)
riverctl map normal Super Down send-layout-cmd rivertile "main-location left"

# Swap focused window with the next/previous one in the stack
riverctl map normal Super+bracketright swap next
riverctl map normal Super+bracketleft swap previous


# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle floatG
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super+Shift+Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'


# --- Media Control (Playerctl) ---
riverctl map normal None XF86AudioMedia spawn "playerctl play-pause"
riverctl map normal None XF86AudioPlay  spawn "playerctl play-pause"
riverctl map normal None XF86AudioPrev  spawn "playerctl previous"
riverctl map normal None XF86AudioNext  spawn "playerctl next"

# --- Brightness Control (Brightnessctl) ---
riverctl map normal None XF86MonBrightnessUp   spawn "brightnessctl set +5%"
riverctl map $mode None XF86MonBrightnessDown spawn "brightnessctl -n 0 set 5%-"
done

# --- Hardware & Media Keys ---
# This loop makes these keys work even when the screen is locked
for mode in normal locked
do
    # Audio (Side keys & Standard keys)
    riverctl map normal None XF86AudioRaiseVolume spawn "pulsemixer --change-volume +5"
    riverctl map normal None XF86AudioLowerVolume spawn "pulsemixer --change-volume -5"
    riverctl map normal None XF86AudioMute        spawn "pulsemixer --toggle-mute"
    riverctl map normal None XF86AudioMicMute     spawn "pulsemixer --id source-0 --toggle-mute"

    # Brightness (F10/F11)
    riverctl map $mode None XF86MonBrightnessUp   spawn "brightnessctl set +5%"
    riverctl map $mode None XF86MonBrightnessDown spawn "brightnessctl set 5%-"

    # Media Controls
    riverctl map $mode None XF86AudioMedia spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPlay  spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPrev  spawn "playerctl previous"
    riverctl map $mode None XF86AudioNext  spawn "playerctl next"
done

# --- Browser & Apps ---
riverctl map normal Super B spawn "brave --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations,WebRTCPipeWireCapturer --disable-gpu-sandbox --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy"

riverctl map normal Super S spawn 'nohup steam >/dev/null 2>&1 & disown'

# F9: Bluetooth Toggle (Using rfkill)
    riverctl map $mode None XF86Bluetooth spawn "rfkill toggle bluetooth"

    # F1: Full Speed Mode (Mapped as a generic launch key for now)
    riverctl map $mode None XF86Launch1 spawn "notify-send 'Alienware F1 Pressed!'"

# Set background and border color
riverctl background-color 0x184A43
riverctl border-color-focused 0xFF00FFC
riverctl border-color-unfocused 0x6F00FF

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl spawn "rivertile -view-padding 2 -outer-padding 2"
riverctl default-layout rivertile
riverctl map normal Super B spawn "brave --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --disable-gpu-sandbox"
